### ISSUE TITLE
[BUG] Many errors in project after importing package

### ISSUE THREAD

**Issue by Joelspeanuts** [Orange-Panda/Rewired-Glyphs#16]
**Bug Description**
After importing the Rewired Glyphs package, I get 26 errors in the console. Unity will not enter play mode, prompting me to fix all compiler errors first. But the errors do not show up in Visual Studio, only in the Unity Console. This first happened in a project I was working on. Tested it in empty project and it happened there as well.

**Reproduction Steps**
1. Create new project in Unity 2020.3.25f1
2. Import Rewired (1.1.55.0)
3. Import TMP Essentials
4. Import Rewired Glyphs using Package manager -> Add Package from Git URL -> https://github.com/Orange-Panda/Rewired-Glyphs.git

**Expected Behavior**
Successful import. No errors in console.

**Example**
Screenshot of errors:
![Screenshot 2024-06-24 225531](https://github.com/Orange-Panda/Rewired-Glyphs/assets/10670540/653b98fe-2129-48fc-9611-18b770ffd2ae)

Text examples of errors:
> Library\PackageCache\com.lmirman.rewiredglyphs@8507d6c50f\Runtime\Components\GlyphRichTextFormatter.cs(200,65): error CS1026: ) expected
>Library\PackageCache\com.lmirman.rewiredglyphs@8507d6c50f\Runtime\Components\GlyphDisplay.cs(170,58): error CS1026: ) expected
>Library\PackageCache\com.lmirman.rewiredglyphs@8507d6c50f\Runtime\API\RewiredGlyphManager.cs(93,57): error CS1003: Syntax error, ',' expected
>Library\PackageCache\com.lmirman.rewiredglyphs@8507d6c50f\Runtime\Components\GlyphRichTextFormatter.cs(203,6): error CS8641: 'else' cannot start a statement.

**Technical Information:**
 - Operating System and Version: Windows 11
 - Unity Version: 2020.3.25f1

**Additional Information**
I think these errors are so strange. They don't seem like "real" errors. so I suspect it can have something to do with the dev environment, some hidden settings in unity about namespaces or some other oddball technicality, but right now I am at a loss.

**Comment by Orange-Panda** [comment]
This is a result of my usage of C# 9.0 features which I didn't realize where exclusive to [Unity 2021.2+](https://docs.unity3d.com/2021.2/Documentation/Manual/CSharpCompiler.html) I am going to update these scripts to allow the package to work on some older C# implementations

**Comment by Orange-Panda** [comment]
I have published a new release [2.2.0](https://github.com/Orange-Panda/Rewired-Glyphs/releases/tag/2.2.0) which addresses this issue. 

For any other readers: going forward C# 8.0 is the minimum C# version this package is developed on so any Unity release older than `2020.3` is not officially supported by this package.

**Comment by Joelspeanuts** [comment]
Omg, this fixed it! Thanks. I live in Norway, so my experience was: Report issue around midnight, go to sleep, wake up finding the issue resolved. Awesome! Thank you for the quick support ❤️
