### ISSUE TITLE
[BUG] - GlyphRichTextFormatter NullReferenceException when invoking SetFormattedText before Awake is called

### ISSUE THREAD

**Issue by SideSwipe9th** [Orange-Panda/Rewired-Glyphs#17]
**Bug Description**
GlyphRichTextFormatter throws a NullReferenceException on line 130, if you invoke SetFormattedText via another script, before GlyphRichTextFormatter has called its own Awake function. This prevents you from pre-setting the formatted text on a GameObject with a GlyphRichTextFormatter when that GameObject starts the scene in a disabled/inactive state.

**Reproduction Steps**
1. Create a GameObject with TMP_Text and GlyphRichTextFormatter components
2. Disable the GameObject created in step 1. 
3. Create another GameObject 
4. Attach a MonoBehaviour to the GameObject created in step 2, that in it's Start function invokes GlyphRichTextFormatter.SetFormattedText on the GameObject created in step 1 
5. Enter Play mode in the editor
6. NullReferenceException is thrown on GlyphRichTextFormatter at line 130

**Expected Behavior**
No NullReferenceException should be thrown, and GlyphRichTextFormatter should allow you to pre-set the formatted text on a GameObject that is either disabled at game or scene start or initialised at runtime.

**Technical Information(please complete the following information):**
 - Operating System and Version: Windows 11 23H2 (OS Build 22631.4602)
 - Unity Version: 2022.3.44f1
 - Rewired Version: 1.1.57.2.U2022
 - Rewired-Glyphs Version: 2.2.0

**Additional Information**
From looking at the code, it seems as though the easiest fix is to wrap GlyphRichTextFormatter line 130 in a null check, before trying to invoke the TMP_Text's SetText function. The SetFormattedText function is otherwise already set up to allow you to pre-format the text via another MonoBehaviour invoking that function, as it caches whatever is passed into it to the private lastPreformatText variable. And because in OnEnable will eventually call SetFormattedText while passing in the value of lastPreformatText everything then works as intended when the GameObject is eventually enabled. 

I've tested this change with the copy of Rewired-Glyphs in my project and haven't noticed any issues with this suggested fix.

**Comment by Orange-Panda** [comment]
Pushed a new release [2.2.1](https://github.com/Orange-Panda/Rewired-Glyphs/releases/tag/2.2.1) that addresses this behavior. Thank you for your report let me know if you encounter other issues.
