### ISSUE TITLE
[BUG] - Crashes completely when adding Image Output with Rewired Input Manager in Prefab Mode

### ISSUE THREAD

**Issue by tobar-io** [Orange-Panda/Rewired-Glyphs#3]
Rewired: You are attemping to access an object that was created by a previous session or different instance of Rewired and is no longer valid. When Rewired is reset or the Rewired Input Manager is disabled or destroyed, all old object references become invalid and can no longer be used. If you deinitialize Rewired, you cannot use locally stored Rewired objects obtained prior to deinitialization and you must get new objects from the Rewired API.
------- Rewired System Info -------
Unity version: 2022.3.5f1
Rewired version: 1.1.45.0.U2022
Platform: Windows
Editor Platform: Windows
Using Unity input: False
Primary input source: RawInput
Use XInput: True
Native mouse handling: True
Enhanced device support: True

UnityEngine.Logger:LogError (string,object)
Rewired.Logger:LogErrorNow (object,bool)
Rewired.Logger:LogError (object,bool)
Rewired.Logger:LogError (object)
Rewired.ReInput:CheckInitialized (int)
Rewired.Player/ControllerHelper:GetLastActiveController ()
LMirman.RewiredGlyphs.InputGlyphs:GetCurrentGlyph (Rewired.Player,int,Rewired.Pole,Rewired.AxisRange&) (at ./Library/PackageCache/com.lmirman.rewiredglyphs@2676334172/Runtime/API/InputGlyphs.cs:128)
LMirman.RewiredGlyphs.InputGlyphs:GetCurrentGlyph (int,Rewired.Pole,Rewired.AxisRange&,int) (at ./Library/PackageCache/com.lmirman.rewiredglyphs@2676334172/Runtime/API/InputGlyphs.cs:120)
LMirman.RewiredGlyphs.Components.GlyphDisplay:UpdateGlyph () (at ./Library/PackageCache/com.lmirman.rewiredglyphs@2676334172/Runtime/Components/GlyphDisplay.cs:60)
LMirman.RewiredGlyphs.Components.GlyphDisplay:InputGlyphsOnRebuildGlyphs () (at ./Library/PackageCache/com.lmirman.rewiredglyphs@2676334172/Runtime/Components/GlyphDisplay.cs:54)
LMirman.RewiredGlyphs.InputGlyphs:InvokeRebuild (bool) (at ./Library/PackageCache/com.lmirman.rewiredglyphs@2676334172/Runtime/API/InputGlyphs.cs:329)
LMirman.RewiredGlyphs.RewiredGlyphManager:Update () (at ./Library/PackageCache/com.lmirman.rewiredglyphs@2676334172/Runtime/API/RewiredGlyphManager.cs:58)

**Comment by tobar-io** [comment]
Happens also with Glyph TMP Rich Text Formatter and others. Maybe a compatibility problem with my Rewired Version?

**Comment by Orange-Panda** [comment]
This may be an issue with how some rewired references were cached in the package. I'll work on a fix now

**Comment by Orange-Panda** [comment]
I've published a new release `v1.1.0` that I believe addresses this issue

**Comment by tobar-io** [comment]
Yes, awesome. Thank you!
