### ISSUE TITLE
[BUG] - GlyphRichTextFormatter not updating glyphs when inactive

### ISSUE THREAD

**Issue by rubmon64** [Orange-Panda/Rewired-Glyphs#5]
**Bug Description**
GlyphRichTextFormatter is not updated if set to inactive in the same frame the input type changes

**Reproduction Steps**
1. Have a Rewired action (e.g. Cancel) mapping to "B" for xbox controller or "ESC" for keyboard
2. Have a window with a button with a GlyphRichTextFormatter label for that action (<glyph "Cancel">Cancel)
3. Use the gamepad input so the button updates the glyph accordingly.
4. Press ESC to close the window and then open again via keyboard input.
5. The GlyphRichTextFormatter will show the glyph for gamepad input.

**Expected Behavior**
At step 5, the text should show the glyph for keyboard.

**Technical Information(please complete the following information):**
 - Unity Version: 2022.3.12f1

**Possible Solution**
Update the glyphs on the GlyphRichTextFormatter 's OnEnable method.
This bug may also happen in the other glyph displaying components.

**Comment by Orange-Panda** [comment]
I have posted a fix in the latest release: `v1.3.0`. Updating to this new version will fix this issue out of the box without any changes needed in your project.

Fortunately this bug only appears to be present in `GlyphRichTextFormatter`.
